In [12]:
import io
import os
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
from scipy import fftpack
from scipy import ndimage
from sklearn import svm, metrics
import keras
from sklearn.metrics import classification_report, confusion_matrix
import imageio
import matplotlib.image as mpimage
import cv2
import glob
import h5py
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
import datetime as dt
from six.moves import range

In [13]:
h5f_data=h5py.File('/home/csed/ELC_activity/output_train_svm/data.h5','r')
h5f_label=h5py.File('/home/csed/ELC_activity/output_train_svm/labels.h5','r')


In [14]:
global_features_string_train= h5f_data['dataset_1']
global_labels_string_train=h5f_label['dataset_1']
global_features_train=np.array(global_features_string_train)
global_labels_train=np.array(global_labels_string_train)


In [15]:
h5f_data.close()
h5f_label.close()

In [16]:
print("[Status] training feature shape: {}".format(global_features_train.shape))

print("[Status] labels shape: {}".format(global_labels_train.shape))

[Status] training feature shape: (493, 1024)
[Status] labels shape: (493,)


In [17]:
num_category = 5
# convert class vectors to binary class matrices
#y_train = keras.utils.to_categorical(global_labels_train, num_category)


In [23]:
clf = svm.SVC(kernel='linear')

In [21]:
from sklearn.model_selection import KFold

In [22]:
cv = KFold(n_splits=10, random_state=1, shuffle=True)

In [26]:
scores = cross_val_score(clf,global_features_train,global_labels_train , scoring='accuracy', cv=cv, n_jobs=-1)

In [28]:
from numpy import mean
from numpy import std
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Accuracy: 0.988 (0.013)


In [30]:
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(clf, global_features_train,global_labels_train , cv=10)
conf_mat = confusion_matrix(global_labels_train, y_pred)


In [31]:
print("Confusion matrix:\n%s" % conf_mat)


Confusion matrix:
[[100   0   0   0   0]
 [  0 100   0   0   0]
 [  1   0  99   0   0]
 [  0   0   0  93   0]
 [  2   0   0   0  98]]


In [33]:
cv = KFold(n_splits=2, random_state=1, shuffle=True)
scores = cross_val_score(clf,global_features_train,global_labels_train , scoring='accuracy', cv=cv, n_jobs=-1)
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))
y_pred = cross_val_predict(clf, global_features_train,global_labels_train , cv=10)
conf_mat = confusion_matrix(global_labels_train, y_pred)
print("Confusion matrix:\n%s" % conf_mat)


Accuracy: 0.988 (0.004)
Confusion matrix:
[[100   0   0   0   0]
 [  0 100   0   0   0]
 [  1   0  99   0   0]
 [  0   0   0  93   0]
 [  2   0   0   0  98]]


In [34]:
print(scores)

[0.99190283 0.98373984]


In [35]:
cv = KFold(n_splits=3, random_state=1, shuffle=True)
scores = cross_val_score(clf,global_features_train,global_labels_train , scoring='accuracy', cv=cv, n_jobs=-1)
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))
y_pred = cross_val_predict(clf, global_features_train,global_labels_train , cv=10)
conf_mat = confusion_matrix(global_labels_train, y_pred)
print("Confusion matrix:\n%s" % conf_mat)


Accuracy: 0.992 (0.008)
Confusion matrix:
[[100   0   0   0   0]
 [  0 100   0   0   0]
 [  1   0  99   0   0]
 [  0   0   0  93   0]
 [  2   0   0   0  98]]


In [36]:
print(scores)

[1.         0.98170732 0.99390244]


In [37]:
cv = KFold(n_splits=4, random_state=1, shuffle=True)
scores = cross_val_score(clf,global_features_train,global_labels_train , scoring='accuracy', cv=cv, n_jobs=-1)
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))
y_pred = cross_val_predict(clf, global_features_train,global_labels_train , cv=10)
conf_mat = confusion_matrix(global_labels_train, y_pred)
print("Confusion matrix:\n%s" % conf_mat)


Accuracy: 0.992 (0.006)
Confusion matrix:
[[100   0   0   0   0]
 [  0 100   0   0   0]
 [  1   0  99   0   0]
 [  0   0   0  93   0]
 [  2   0   0   0  98]]


In [38]:
print(scores)

[1.         0.98373984 0.99186992 0.99186992]


In [39]:
cv = KFold(n_splits=5, random_state=1, shuffle=True)
scores = cross_val_score(clf,global_features_train,global_labels_train , scoring='accuracy', cv=cv, n_jobs=-1)
print('Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))
y_pred = cross_val_predict(clf, global_features_train,global_labels_train , cv=10)
conf_mat = confusion_matrix(global_labels_train, y_pred)
print("Confusion matrix:\n%s" % conf_mat)


Accuracy: 0.994 (0.005)
Confusion matrix:
[[100   0   0   0   0]
 [  0 100   0   0   0]
 [  1   0  99   0   0]
 [  0   0   0  93   0]
 [  2   0   0   0  98]]


In [40]:
print(scores)

[1.         0.98989899 0.98989899 1.         0.98979592]
